// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: followed_feeds.sql

package database

import (
	"context"
)

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT feeds.name
FROM feeds
INNER JOIN feed_follows ON feeds.id = feed_follows.feed_id
INNER JOIN users ON feed_follows.user_id = users.id
WHERE users.name = $1
`

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
