// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mark_fetched.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds
SET last_fetched = $2, updated_at = $3
WHERE feeds.id = $1
`

type MarkFeedFetchedParams struct {
	ID          uuid.UUID
	LastFetched sql.NullTime
	UpdatedAt   time.Time
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, arg.ID, arg.LastFetched, arg.UpdatedAt)
	return err
}
